### ISSUE TITLE
Module not found error when installing

### ISSUE THREAD

**Issue by yy** [Hoosier-Clusters/clusim#2]
```
$ python3 setup.py install
DendroPY not supported.
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import clusim
  File "/Users/yy/git/clusim/clusim/__init__.py", line 5, in <module>
    from clusim.clugen import *
  File "/Users/yy/git/clusim/clusim/clugen.py", line 5, in <module>
    import mpmath
ModuleNotFoundError: No module named 'mpmath'
```

**Comment by yy** [comment]
Is this because `__init__.py` imports clusim package?

**Comment by ajgates42** [comment]
I think the problem was in setup.py .  Can you try it now?

**Comment by yy** [comment]
I'm still getting an error from `from clusim import __package__, __description__, __version__`

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xb/7k4mj0yn6fx6f67t1rv3jmvxncy8kk/T/pip-req-build-sb4768dq/setup.py", line 6, in <module>
        from clusim import __package__, __description__, __version__
      File "/private/var/folders/xb/7k4mj0yn6fx6f67t1rv3jmvxncy8kk/T/pip-req-build-sb4768dq/clusim/__init__.py", line 18, in <module>
        from clusim.clugen import *
      File "/private/var/folders/xb/7k4mj0yn6fx6f67t1rv3jmvxncy8kk/T/pip-req-build-sb4768dq/clusim/clugen.py", line 3, in <module>
        import mpmath
    ModuleNotFoundError: No module named 'mpmath'
    DendroPY not supported.
```

**Comment by yy** [comment]
now it installs fine, but with some warnings:

    warning: no files found matching '*.html' under directory 'doc'
    warning: no files found matching '*.css' under directory 'doc'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.svn' found anywhere in distribution
    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching 'doc/auto_examples'
    no previously-included directories found matching 'doc/modules'
    no previously-included directories found matching 'doc/reference/generated'
    no previously-included directories found matching 'doc/reference/algorithms/generated'
    no previously-included directories found matching 'doc/reference/classes/generated'
    no previously-included directories found matching 'doc/reference/readwrite/generated'
